using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

public class GridManager : MonoBehaviour
{
    public class CellData
    {
        public bool isPassable;
        public GameObject containedInCell; 
    }



    public int width;
    public int height;
    public float xStart;
    public float yStart;
    public float xSpace;
    public float ySpace;
    public int cellSize;
    public Transform roomContainer;
    private GameObject[,] gridArray;
    private GameObject spawnPoint;

    //A mettre dans un script à part 
    public CharacterController character;
    
    [Header("Tiles")]
    [Header("Corners")]
    public GameObject[] cornerTopLeftTiles;
    public GameObject[] cornerTopRightTiles;
    public GameObject[] cornerBottomLeftTiles; 
    public GameObject[] cornerBottomRightTiles;

    [Header("Content")]
    public GameObject[] topTiles;
    public GameObject[] bottomTiles;
    public GameObject[] leftTiles;
    public GameObject[] rightTiles;
    public GameObject[] centerTiles;

    private Grid grid;
    public bool isAutoGenerated;
    public Tilemap murTileMap;
    public Tilemap solTileMap;
    private CellData[,] cellDatas;

    private void InitCellDatas()
    {
        solTileMap.CompressBounds();
        Vector3Int tilemapSize = solTileMap.size;
        Debug.Log(tilemapSize.ToString());
        cellDatas = new CellData[tilemapSize.x, tilemapSize.y];

        for (int j = 0; j < tilemapSize.y; j++)
        {

            for (int i = 0; i < tilemapSize.x; i++)
            {
                cellDatas[i, j] = new CellData();
                Vector3Int gridPosition = new Vector3Int(i,j,0);

                if (!solTileMap.HasTile(gridPosition) || murTileMap.HasTile(gridPosition))
                {
                    cellDatas[i,j].isPassable = false;
                }
                else
                {
                    cellDatas[i,j].isPassable = true;
                }
            }
        }
    }

    public bool CanMoveOnCell(Vector3Int cell)
    {
        CellData cellData = GetCellData(cell);

        if (cellData != null && cellData.isPassable)
        {
            return true;
           
        }

        return false;
    }

    public bool IsObjectOnCell(Vector3Int cell)
    {
        CellData cellData = GetCellData(cell);

        if(cellData != null && cellData.containedInCell != null)
        {
            return true;
        }

        return false;
    }

    public CellData GetCellData(Vector3Int cell)
    {
        Vector3Int tilemapSize = solTileMap.size;

        if (cell.x < 0 || cell.x >= tilemapSize.x
            || cell.y < 0 || cell.y >= tilemapSize.y)
        {
            return null;
        }

        return cellDatas[cell.x, cell.y];
    }

    public void SetCell(int x, int y)
    {
        RoomTile prevTile;
        RoomTile underTile;
        GameObject randomRoom;


        //Coins
        //Coin BG
        if( x == 0 && y == 0)
        {
            randomRoom = this.SetRoom(cornerBottomLeftTiles, 0, 0);
        }
        //Coin HG
        else if( x == 0 && y == (height - 1))
        {
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(cornerTopLeftTiles, underTile.numberDoorsTop, 0);
        }
        //Coin BD
        else if( x == (width - 1) && y == 0 )
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(cornerBottomRightTiles, 0, prevTile.numberDoorsRight);

        }
        //Coin HD
        else if( x == (width - 1) && y == (height - 1))
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(cornerTopRightTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }
        //Cotés
        //G
        else if( x == 0 )
        {
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(leftTiles, underTile.numberDoorsTop, 0);
        }
        //D
        else if( x == (width - 1)  )
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(rightTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }
        //H
        else if( y == (height - 1))
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(topTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }
        //B
        else if( y == 0 )
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(bottomTiles, 0, prevTile.numberDoorsRight);
        }
        //Centre
        else
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(centerTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }

        //Ajout de la room dans le tableau
        gridArray[x, y] = randomRoom;

        Tilemap source;
        Tilemap destination;
        Vector3Int offsetPosition = GetWorldPosition(x, y);
        Vector2 roomSize = new(cellSize, cellSize);

        //Pour chaque layer/tilemap dans le prefab
        for (int k =  0; k < roomContainer.childCount; k++) {

            // /!\ Attention si on change l'arborescence des prefabs
            source = randomRoom.transform.GetChild(0).GetChild(k).GetComponent<Tilemap>();
            destination = roomContainer.GetChild(k).GetComponent<Tilemap>();

            //Copie des tiles du préfab dans la destination
            CopyTilemap(source, destination, offsetPosition, roomSize);
        }

        //Si un SpawnPoint existe dans cette room
        if(randomRoom.transform.childCount > 1)
        {
            if(randomRoom.transform.GetChild(1).name == "SpawnPoint")
            {
                spawnPoint = randomRoom.transform.GetChild(1).gameObject;
            }
        }
    }

    private void CopyTilemap(Tilemap source, Tilemap destination, Vector3Int roomPosition, Vector2 roomSize)
    {

        Vector3Int tilePosition;
        for (int i = 0; i < roomSize.x; i++)
        {
            for (int j = 0; j < roomSize.y; j++)
            {
                tilePosition = new Vector3Int(i, j, 0);

                destination.SetTile(roomPosition + tilePosition, source.GetTile(tilePosition));
            }
        }
    }

    private GameObject SetRoom(GameObject[] tiles, int numberDoorsBottom, int numberDoorsLeft)
    {

        List<GameObject> listTile = new List<GameObject>();
        int randomIndex;
        RoomTile tile;

        for (int i = 0; i < tiles.Length; i++)
        {
            tile = tiles[i].GetComponent<RoomTile>();
            
            if((tile.numberDoorsBottom == numberDoorsBottom && tile.numberDoorsLeft == numberDoorsLeft) || (tile.numberDoorsBottom == 0 && tile.numberDoorsLeft == 0))
            {
                listTile.Add(tiles[i]);
            }
        }

        randomIndex = Random.Range(0,listTile.Count );
        
        return listTile[randomIndex];

    }
    
    public Vector3Int GetWorldPosition(int x, int y)
    {
        return new Vector3Int((int)(xStart + (xSpace * x)), (int)(yStart + ( ySpace * y ))) * cellSize;
    }

    public Vector3Int WorldToCell(Vector2 worldPosition)
    {
        return grid.WorldToCell(worldPosition);
    }

    public Vector3 CellToWorld(Vector3Int cellPosition)
    {
        return grid.GetCellCenterWorld(cellPosition);
    }

    public bool IsObstacleBetween(Vector3Int start, Vector3Int end, Vector2 direction)
    {
        float distance = Vector3Int.Distance(start, end);
        Vector3Int checkPosition = start;

        for (int i = 1; i < distance; i++)
        {
            checkPosition += Vector3Int.FloorToInt((Vector3)direction);
            if (!CanMoveOnCell(checkPosition))
            {
                return true; // Il y a un obstacle
            }
        }
        return false; // Pas d'obstacle
    }


    private void Awake()
    {

        grid = this.gameObject.GetComponent<Grid>();

        gridArray = new GameObject[width, height];

        if (isAutoGenerated)
        {

            for (int x = 0; x < width; x++)
            {
                for (int y = 0; y < height; y++)
                {
                    this.SetCell(x, y);
                }
            }

            //A mettre dans un script à part 
            //Ajoute le personnage au spawnpoint
            Instantiate(character, spawnPoint.transform.position, Quaternion.identity);
        }

        InitCellDatas();
    }
    private void Start()
    {
        
       // LogGridArray();
    }

    private void Update()
    {

    }

    private void LogGridArray()
    {
        string log = "";

        for(int y = 0; y < cellDatas.GetLength(1); y++)
        {
            for (int x = 0; x < cellDatas.GetLength(0); x++)
            {
                //log += " " + "(" + x + "," + y + ")";
                if (cellDatas[x, y].isPassable)
                {
                    //log += " "+CellToWorld(new Vector3Int(x,y,0)).ToString();
                    log += " 0";
                } 
                else
                {
                    log += " 1";
                }
            }
            log += " \n";
        }

        Debug.Log(log);
    }

    public void DebugCellWithObjects()
    {
        Debug.Log("---------------------------------------");

        for (int y = 0; y < cellDatas.GetLength(1); y++)
        {
            for (int x = 0; x < cellDatas.GetLength(0); x++)
            {
                if (cellDatas[x, y].containedInCell != null)
                {
                    Debug.Log("( " + x + "," + y + " )");
                }
            }
        }
    }

}
