using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

public class MapBuilder : MonoBehaviour
{
 /*   public class CellData
    {
        public bool isPassable;
        public GameObject containedInCell; 
    }
 */

    public int width;
    public int height;
    public float xStart;
    public float yStart;
    public float xSpace;
    public float ySpace;
    public int cellSize;
    public List<SpawnPoint> spawnPoints;
    public Transform roomContainer;
    private GameObject[,] gridArray;
    private GameObject spawnPoint;

    //A mettre dans un script à part 
    //public PlayerController player;
    
    [Header("Tiles")]
    [Header("Corners")]
    public GameObject[] cornerTopLeftTiles;
    public GameObject[] cornerTopRightTiles;
    public GameObject[] cornerBottomLeftTiles; 
    public GameObject[] cornerBottomRightTiles;

    [Header("Content")]
    public GameObject[] topTiles;
    public GameObject[] bottomTiles;
    public GameObject[] leftTiles;
    public GameObject[] rightTiles;
    public GameObject[] centerTiles;

    private Grid grid;
    public bool isAutoGenerated;


    private void Awake()
    {
        width = GameManager.Instance.GetLevelMapSizeX();
        height = GameManager.Instance.GetLevelMapSizeY();
        //numberEnemies = GameManager.Instance.GetLevelNumberEnemies();

        grid = this.gameObject.GetComponent<Grid>();

        gridArray = new GameObject[width, height];

        if (isAutoGenerated)
        {

            for (int x = 0; x < width; x++)
            {
                for (int y = 0; y < height; y++)
                {
                    this.SetCell(x, y);
                }
            }
        }
    }


    public void SetCell(int x, int y)
    {
        RoomTile prevTile;
        RoomTile underTile;
        GameObject randomRoom;


        //Coins
        //Coin BG
        if( x == 0 && y == 0)
        {
            randomRoom = this.SetRoom(cornerBottomLeftTiles, 0, 0);
        }
        //Coin HG
        else if( x == 0 && y == (height - 1))
        {
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(cornerTopLeftTiles, underTile.numberDoorsTop, 0);
        }
        //Coin BD
        else if( x == (width - 1) && y == 0 )
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(cornerBottomRightTiles, 0, prevTile.numberDoorsRight);

        }
        //Coin HD
        else if( x == (width - 1) && y == (height - 1))
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(cornerTopRightTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }
        //Cotés
        //Gauche
        else if( x == 0 )
        {
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(leftTiles, underTile.numberDoorsTop, 0);
        }
        //Droit
        else if( x == (width - 1)  )
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(rightTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }
        //Haut
        else if( y == (height - 1))
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(topTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }
        //Bas
        else if( y == 0 )
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(bottomTiles, 0, prevTile.numberDoorsRight);
        }
        //Centre
        else
        {
            prevTile = gridArray[x-1, y].GetComponent<RoomTile>();
            underTile = gridArray[x, y-1].GetComponent<RoomTile>();
            randomRoom = this.SetRoom(centerTiles, underTile.numberDoorsTop, prevTile.numberDoorsRight);
        }

        //Ajout de la room dans le tableau
        gridArray[x, y] = randomRoom;

        Tilemap source;
        Tilemap destination;
        Vector3Int offsetPosition = GetWorldPosition(x, y);
        Vector2 roomSize = new(cellSize, cellSize);

        //Pour chaque layer/tilemap dans le prefab
        for (int k =  0; k < roomContainer.childCount; k++) {

            // /!\ Attention si on change l'arborescence des prefabs
            source = randomRoom.transform.GetChild(0).GetChild(k).GetComponent<Tilemap>();
            destination = roomContainer.GetChild(k).GetComponent<Tilemap>();

            //Copie des tiles du préfab dans la destination
            CopyTilemap(source, destination, offsetPosition, roomSize);
        }

        //Si un SpawnPoint ou une Sortie existe dans cette room
        if(randomRoom.transform.childCount > 1)
        {
            //Recherche de tous les enfants de la room
            foreach (Transform child in randomRoom.transform)
            {
                //Vérification si l'enfant est un SpawnPoint ou une Sortie
                if (child.GetComponent<SpawnPoint>() != null)
                {
                    //Ajout du SpawnPoint à la liste des SpawnPoints
                    spawnPoint = child.gameObject;
                    spawnPoint.GetComponent<SpawnPoint>().point = new Vector2(spawnPoint.transform.position.x + (x * cellSize * xSpace), spawnPoint.transform.position.y + (y * cellSize * ySpace));
                    spawnPoints.Add(spawnPoint.GetComponent<SpawnPoint>());
                }
                else if(child.GetComponent<LevelExitController>() != null)
                {
                    //Instantiation de la sortie au bon endroit
                    Instantiate(child.gameObject, new Vector2(child.position.x + (x * cellSize * xSpace), child.position.y + (y * cellSize * ySpace)), Quaternion.identity);
                }   
            }

            //OLD CODE
            /* if (randomRoom.transform.GetChild(1).name == "SpawnPoint" || randomRoom.transform.GetChild(1).GetComponent<SpawnPoint>() != null)
             {
                 spawnPoint = randomRoom.transform.GetChild(1).gameObject;

                 spawnPoint.GetComponent<SpawnPoint>().point = new Vector2(spawnPoint.transform.position.x + (x * cellSize * xSpace), spawnPoint.transform.position.y + (y * cellSize * ySpace));
                 spawnPoints.Add(spawnPoint.GetComponent<SpawnPoint>());

             }*/
        }
    }

    private void CopyTilemap(Tilemap source, Tilemap destination, Vector3Int roomPosition, Vector2 roomSize)
    {

        Vector3Int tilePosition;
        for (int i = 0; i < roomSize.x; i++)
        {
            for (int j = 0; j < roomSize.y; j++)
            {
                tilePosition = new Vector3Int(i, j, 0);

                destination.SetTile(roomPosition + tilePosition, source.GetTile(tilePosition));
            }
        }
    }

    private GameObject SetRoom(GameObject[] tiles, int numberDoorsBottom, int numberDoorsLeft)
    {

        List<GameObject> listTile = new List<GameObject>();
        int randomIndex;
        RoomTile tile;

        for (int i = 0; i < tiles.Length; i++)
        {
            tile = tiles[i].GetComponent<RoomTile>();
            
            if((tile.numberDoorsBottom == numberDoorsBottom && tile.numberDoorsLeft == numberDoorsLeft) || (tile.numberDoorsBottom == 0 && tile.numberDoorsLeft == 0))
            {
                listTile.Add(tiles[i]);
            }
        }

        randomIndex = Random.Range(0,listTile.Count );
        
        return listTile[randomIndex];

    }
    
    public Vector3Int GetWorldPosition(int x, int y)
    {
        return new Vector3Int((int)(xStart + (xSpace * x)), (int)(yStart + ( ySpace * y ))) * cellSize;
    }


}
